---
name: Wakatime Generator

'on':
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: deedee
    steps:
      - uses: ajgon/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_API_URL: https://wakapi.rzegocki.dev
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          COMMIT_MESSAGE: "chore: update README.md"
          DEBUG_LOGGING: "True"
          DEFAULT_TIMEZONE: "Europe/Warsaw"
          IGNORED_REPOS: "nixpkgs"  # too big

          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "True"
